apiVersion: apps/v1
kind: Deployment
metadata:
  name: tailscale-auth-test
  namespace: tailscale-auth-test
  labels:
    app: tailscale-auth-test
spec:
  selector:
    matchLabels:
      app: tailscale-auth-test
  replicas: 3
  template:
    metadata:
      labels:
        app: tailscale-auth-test
    spec:
      containers:
      - name: tailscale-auth-test
        image: registry.hub.docker.com/clarkezone/tsgunicorn:latest
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        ports:
        - containerPort: 8000