apiVersion: tailscale.com/v1alpha1
kind: Connector
metadata:
  name: exit-node
  namespace: tailscale
spec:
  hostname: ts-exit-node
  exitNode: true
  subnetRouter:
    advertiseRoutes:
      - "192.168.1.0/24"