resources:
  - secret.yaml
  - connector.yaml # Tailscale exit node

helmCharts:
  - name: tailscale-operator
    repo: https://pkgs.tailscale.com/helmcharts
    version: 1.80.0
    releaseName: tailscale-operator
    namespace: tailscale