apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: prometheus-operator-crds
    releaseName: prometheus-operator-crds
    version: 18.0.0
    repo: https://prometheus-community.github.io/helm-charts
    namespace: monitoring