apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ftb-evolution-data
  namespace: minecraft
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 15Gi