resources:
  - ingress.yaml

helmCharts:
  - name: tailscale-operator
    repo: https://charts.longhorn.io/
    version: v1.8.0
    releaseName: longhorn
    namespace: longhorn-system
    valuesFile: values.yaml