apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ingress.yaml
helmCharts:
  - name: longhorn
    repo: https://charts.longhorn.io/
    version: v1.8.0
    releaseName: longhorn
    namespace: longhorn
    valuesFile: values.yaml