apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: trilium-data
  namespace: notes
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi