controllers:
  main:
    containers:
      trilium:
        image:
          repository: triliumnext/trilium
          tag: v0.99.1
          pullPolicy: IfNotPresent
        env:
          key: "value"
persistence:
  data:
    enabled: true
    type: persistentVolumeClaim
    existingClaim: trilium-data