controller:
  config:
    ssl-redirect: "true"
    force-ssl-redirect: "true"
  replicaCount: 3
  service:
    type: LoadBalancer
    annotations:
      service.beta.kubernetes.io/oci-load-balancer-shape: "flexible"
      service.beta.kubernetes.io/oci-load-balancer-shape-flex-min: "10"
      service.beta.kubernetes.io/oci-load-balancer-shape-flex-max: "10"
  ingressClassResource:
    name: external
    default: false
    controllerValue: k8s.io/external
  watchIngressWithoutClass: false
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true