controller:
  config:
    ssl-redirect: "true"
    force-ssl-redirect: "true"
  replicaCount: 1
  service:
    type: LoadBalancer
  metrics:
    enabled: false
    serviceMonitor:
      enabled: false