apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
  namespace: download
  labels:
    app: prowlarr
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: prowlarr
  template:
    metadata:
      labels:
        app: prowlarr
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
      containers:
        - name: prowlarr
          image: ghcr.io/home-operations/prowlarr:1.32.2.4987@sha256:77f6b6850d6191f68d2d2d4d21655b103acc5c6f6243d8cb62bb75888499b78a
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: PROWLARR__APP__INSTANCENAME
              value: "Prowlarr"
            - name: PROWLARR__APP__THEME
              value: "dark"
            - name: PROWLARR__AUTH__METHOD
              value: "External"
            - name: PROWLARR__AUTH__REQUIRED
              value: "DisabledForLocalAddresses"
            - name: PROWLARR__LOG__DBENABLED
              value: "False"
            - name: PROWLARR__LOG__LEVEL
              value: "info"
            - name: PROWLARR__SERVER__PORT
              value: "80"
            - name: PROWLARR__UPDATE__BRANCH
              value: "develop"
            - name: TZ
              value: "Europe/London"
          volumeMounts:
            - name: config
              mountPath: /config
            - name: tmp
              mountPath: /tmp
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 1000m
              memory: 1Gi
          livenessProbe:
            httpGet:
              path: /ping
              port: http
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /ping
              port: http
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 3
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: prowlarr-config
        - name: tmp
          emptyDir: {}