- hosts: all
  tasks:
  - name: Update apt-get repo and cache
    apt: update_cache=yes cache_valid_time=3600
    become: true
  - name: Upgrade all apt packages
    apt: upgrade=dist
    become: true