provider:
  name: cloudflare
env:
  - name: CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: cloudflare-api-token
        key: apiKey
txtOwnerId: "external-dns"
domainFilters:
  - "mellor.dev"
policy: sync