replicaCount: 1

strategy:
  type: "RollingUpdate"
  rollingUpdate:
    maxSurge: "100%"
    maxUnavailable: 0

ingress:
  enabled: true
  className: "internal"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    external-dns.alpha.kubernetes.io/hostname: ab.mellor.dev
    kubernetes.io/tls-acme: "true"
  hosts:
    - host: ab.mellor.dev
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: 
  - secretName: ab.mellor.dev
    hosts:
    - ab.mellor.dev

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 1000m
    memory: 1Gi
livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

files:
  dataDirectory: /data
  server: /data/server-files
  user: /data/user-files

persistence:
  enabled: true
  existingClaim: ""
  storageClass: "longhorn"
  accessModes:
    - ReadWriteOnce
  size: 3Gi

volumes: 
- name: data
  persistentVolumeClaim:
    claimName: actualbudget-volume

volumeMounts:
 - name: data
   mountPath: "/data"