apiVersion: apps/v1
kind: Deployment
metadata:
  name: matter-server
  namespace: home-automation
  labels:
    app: matter-server
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: matter-server
  template:
    metadata:
      labels:
        app: matter-server
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet

      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: arch
                    operator: In
                    values:
                      - x86

      containers:
        - name: matter-server
          image: ghcr.io/home-assistant-libs/python-matter-server:8.1.0@sha256:170aa093ce91c76cde4cc390918307590f0f5558fcec93f913af3cb019e6562a
          imagePullPolicy: IfNotPresent
          args:
            - --storage-path
            - /data
            - --port
            - "5580"
          ports:
            - name: ws
              containerPort: 5580
              protocol: TCP
          env:
            - name: TZ
              value: "Europe/London"
          volumeMounts:
            - name: data
              mountPath: /data
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 512Mi
          readinessProbe:
            tcpSocket:
              port: ws
            initialDelaySeconds: 15
            periodSeconds: 15
            timeoutSeconds: 5
          livenessProbe:
            tcpSocket:
              port: ws
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: matter-server-data
