crds:
  enabled: false
defaultRules:
  create: true
grafana:
  enabled: true
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      external-dns.alpha.kubernetes.io/hostname: grafana.mellor.dev
      kubernetes.io/tls-acme: "true"
    ingressClassName: internal
    hosts:
      - grafana.mellor.dev
    tls:
      - secretName: grafana.mellor.dev
        hosts:
          - grafana.mellor.dev
nodeExporter:
  enabled: true
  serviceMonitor:
    relabelings:
      - action: replace
        regex: (.*)
        replacement: $1
        sourceLabels:
          - __meta_kubernetes_pod_node_name
        targetLabel: kubernetes_node