apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - crd.yaml
helmCharts:
  - name: connect
    repo: https://1password.github.io/connect-helm-charts
    version: 1.17.0
    releaseName: 1password-operator
    namespace: 1password-operator
    valuesFile: values.yaml