apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: connect
    repo: https://1password.github.io/connect-helm-charts
    version: 1.17.0
    releaseName: 1password
    namespace: 1password
    valuesFile: values.yaml