apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: metallb
    repo: https://metallb.github.io/metallb
    version: v4.7.6
    releaseName: metallb
    namespace: networking
    valuesFile: values.yaml

resources:
  - ipaddresspool.yaml