apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ipaddresspool.yaml
helmCharts:
  - name: metallb
    repo: https://metallb.github.io/metallb
    version: v0.14.9
    releaseName: metallb
    namespace: networking
    valuesFile: values.yaml