apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: scdl
  namespace: download
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    external-dns.alpha.kubernetes.io/hostname: scdl.mellor.dev
    external-dns.alpha.kubernetes.io/target: external.mellor.dev
    kubernetes.io/tls-acme: "true"
spec:
  ingressClassName: external
  rules:
  - host: scdl.mellor.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: scdl
            port:
              number: 8000
  tls: 
  - secretName: scdl.mellor.dev
    hosts:
    - scdl.mellor.dev