apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scdl-downloads-pvc
  namespace: download
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 3Gi