apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarr-nfs-media
  labels:
    type: nfs
    app: sonarr
spec:
  capacity:
    storage: 10936Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.1.100
    path: /mnt/vol1/media
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-media
  namespace: download
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 10936Gi
  selector:
    matchLabels:
      type: nfs
      app: sonarr
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-config
  namespace: download
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi