all:
  hosts:
    k3s-01:
      ansible_host: ENTER_IP_ADDRESS
    k3s-02:
      ansible_host: ENTER_IP_ADDRESS
    k3s-03:
      ansible_host: ENTER_IP_ADDRESS
    k3s-04:
      ansible_host: ENTER_IP_ADDRESS
    k3s-05:
      ansible_host: ENTER_IP_ADDRESS
  children:
    master:
      hosts:
        k3s-01: {}
    workers:
      hosts:
        k3s-[02:05]: {}
  vars:
    ansible_python_interpreter: /usr/bin/python3