controller:
  config:
    ssl-redirect: "true"
    force-ssl-redirect: "true"
  replicaCount: 3
  service:
    type: LoadBalancer
    loadBalancerClass: tailscale
  ingressClassResource:
    name: internal
    default: true
    controllerValue: k8s.io/internal
  watchIngressWithoutClass: false
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true