apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
  namespace: download
  labels:
    app: qbittorrent
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: qbittorrent
  template:
    metadata:
      labels:
        app: qbittorrent
    spec:
      initContainers:
      - name: init-config-dir
        image: busybox
        command: ["sh", "-c", "chown -R 1000:1000 /config"]
        securityContext:
          runAsUser: 0
        volumeMounts:
        - name: config
          mountPath: /config
      containers:
      - name: qbittorrent
        image: ghcr.io/home-operations/qbittorrent:5.1.2@sha256:31ac39705e31f7cdcc04dc46c1c0b0cdf8dc6f9865d4894efc097a33adc41524
        ports:
        - name: http
          containerPort: 8080
        - name: bittorrent-tcp
          containerPort: 50413
          protocol: TCP
        - name: bittorrent-udp
          containerPort: 50413
          protocol: UDP
        env:
        - name: TZ
          value: "Europe/London"
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: UMASK
          value: "022"
        - name: QBT_WEBUI_PORT
          value: "8080"
        - name: QBT_BT_PORT
          value: "50413"
        - name: QBT_DOWNLOADS_LOCATION
          value: "/media/Downloads"
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
          limits:
            cpu: 2000m
            memory: 2Gi
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
        volumeMounts:
        - name: config
          mountPath: /config
        - name: media
          mountPath: /media
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: qbittorrent-config
      - name: media
        persistentVolumeClaim:
          claimName: qbittorrent-media-nfs