apiVersion: v1
kind: PersistentVolume
metadata:
  name: qbittorent-media-nfs
  labels:
    type: nfs
    app: qbittorrent
spec:
  capacity:
    storage: 10936Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.1.100
    path: /mnt/vol1/media/
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorent-media-nfs
  namespace: download
spec:
  volumeName: qbittorent-media-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10936Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-config
  namespace: download
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn