resources:
  - secret.yaml

helmCharts:
  - name: tailscale-operator
    repo: https://pkgs.tailscale.com/helmcharts
    version: latest
    releaseName: tailscale-operator
    namespace: tailscale
    valuesFile: values.yaml