apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system
helmCharts:
  - name: intel-device-plugins-operator
    repo: https://intel.github.io/helm-charts
    version: 0.28.0
    releaseName: intel-device-plugins-operator
    namespace: kube-system
    includeCRDs: true
    valuesInline:
      nodeFeatureRules: true

  - name: intel-device-plugins-gpu
    repo: https://intel.github.io/helm-charts
    version: 0.28.0
    releaseName: intel-device-plugins-gpu
    namespace: kube-system
    valuesInline:
      deployNodeFeatureRule: false
      sharedDevNum: 2 
      dpdk:
        enabled: false
      monitoring:
        enabled: true
      devicePlugin:
        enable: true
        resourceManager: false