apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 1password-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://1password.github.io/operator/
    chart: 1password-operator
    targetRevision: "latest"
    helm:
      values: |
        namespace: 1password
  destination:
    server: https://kubernetes.default.svc
    namespace: 1password
  syncPolicy:
    automated:
      prune: true
      selfHeal: true