apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 1password-connect-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://1password.github.io/connect-helm-charts
    chart: connect
    targetRevision: 1.17.0
    helm:
      valueFiles:
        - apps/1password-operator/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: 1password
  syncPolicy:
    automated:
      prune: true
      selfHeal: true