apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: internal-ingress-nginx
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/alfiemellor/homelab
    path: apps/network/internal/ingress-nginx
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: network
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true