apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tailscale-auth-test
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/alfiemellor/homelab
    path: apps/tailscale-auth-test
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: tailscale-auth-test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true